---
# role: jomrr.ipv6
# file: molecule/resources/playbooks/verify.yml

- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: "Verify no IPv6 addresses"
      ansible.builtin.assert:
        that:
          - ansible_all_ipv6_addresses | default([]) | length == 0
